# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: CI

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
      - name: "Run PHP lint"
        run: "composer ci:php:lint"
    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-20.04
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      -
        name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-
            composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.composer/cache
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      -
        name: "Install Composer dependencies"
        run: "composer install --no-progress"
      -
        name: "Run command"
        run: "composer ci:${{ matrix.command }}"
    strategy:
      matrix:
        command:
          - "ts:lint"
          - "php:sniff"
        php-version:
          - 7.4
